apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
    - host: api.my-app.com # Change this to your actual domain
      http:
        paths:
          - path: /author
            pathType: Prefix
            backend:
              service:
                name: author-service
                port:
                  number: 80
          - path: /book
            pathType: Prefix
            backend:
              service:
                name: book-service
                port:
                  number: 80
